### ISSUE TITLE
Kata Runtime 3.7, 3.8, 3.9: NVIDIA GPU passthrough failed, but Intel AX200 successful; NVIDIA GPU can be passed through using Proxmox (VFIO)

### ISSUE THREAD

**Issue by acblbtpccc** [kata-containers/kata-containers#10360]
# Get your issue reviewed faster

1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers
[kata-collect-data.sh.2024-09-29-18-03-17.log](https://github.com/user-attachments/files/17178826/kata-collect-data.sh.2024-09-29-18-03-17.log)
2. Hardware Environment:
  GPU: Nvidia RTX2060-12G
  Board: Gigabyte X570 
  CPU: AMD Ryezen 5950x
  RAM: 96GB

# Description of problem

1. On the exactly same host (Debian 12, kernel 6.8), I got errors when I passthrough using kata runtime (with nvidia-gpu kernel provided by kata-container), 
2. At the same time, I had successfully passed through an NVIDIA GPU using Proxmox (VFIO), and passed through an Intel AX200 WiFi Controller successfully (with kata runtime), which is also a PCIe device.
![image](https://github.com/user-attachments/assets/04b57108-d87e-4b77-8a9e-ae664c96ef29)

# Actual result

I found that the behaviour is that, every time I run "ctr run ...":

1. 1st time "ctr run ...": error will be "ctr: failed to create shim task: ttrpc: closed: unknown"
4. 2nd time "ctr run ...": error will be "ctr: failed to create shim task: listen unix /run/vc/vm/arch-6/qmp.sock: bind: address already in use: unknown" 
5. 3rd time "ctr run ...": error will be "ctr: failed to create shim task: QMP command failed: vfio 0000:03:00.0: failed to open /dev/vfio/24: Device or resource busy: unknown"

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/06c6d87d-ae0c-433a-b732-14e77cc881e3">

After 3 times "ctr run...", the further error will always be "QMP command failed: vfio 0000:03:00.0: failed to open /dev/vfio/24: Device or resource busy", and I have to reboot.

# Further information

1. I successfully passed through using VFIO Proxmox 8.2 (Debian 12) to passthrough GPU:

  <img width="706" alt="image" src="https://github.com/user-attachments/assets/f0cf67d4-ca87-4a08-93cf-c68e2210b467">

2. But after running "ctr run ..." for 1 time, I got "ctr: failed to create shim task: ttrpc: closed: unknown" error and then I can't passthrough GPU via Proxmox (VFIO):

  <img width="991" alt="image" src="https://github.com/user-attachments/assets/5dbb2398-f6dc-4945-8278-4c35b0d54ddf">
  <img width="1191" alt="image" src="https://github.com/user-attachments/assets/ea83afc5-66eb-4d95-b98d-1ec6e5acec39">

**Comment by acblbtpccc** [comment]
Hi @zvonkok and @Apokleos,

I'm Alex, and I'm writing to inquire about your insights regarding any potential issues in my Kata configuration TOML file.

1. I used the TOML file from /opt/kata/share/defaults/kata-containers/configuration-qemu-nvidia-gpu.toml and the GPU kernel from /opt/kata/share/kata-containers/vmlinux-6.1.62-135-nvidia-gpu, which are provided by the official Kata Containers repository.
2. I can successfully perform the passthrough using VFIO, which I assume proves that my VFIO configuration is correct. Therefore, I believe the error might be related to the Kata runtime source code, with which I'm not very familiar.

Thank you in advance for your time and assistance. I greatly appreciate any insights or guidance you can provide regarding this issue. Your expertise is invaluable, and I look forward to your response.

**Comment by acblbtpccc** [comment]
I'm also attaching the containerd logs for your reference.
[containerd.error.2024-09-29-18-27-12.log](https://github.com/user-attachments/files/17178872/containerd.error.2024-09-29-18-27-12.log)

**Comment by acblbtpccc** [comment]
@zvonkok, Additionally, I watched your interview videos on [Youtube](https://www.youtube.com/live/urHjDdtuIa4), which were very informative. If possible, would you be willing to share the environment configuration you used? This would be incredibly helpful for us to reference when trying to reproduce the setup.

**Comment by Apokleos** [comment]
Sorry @acblbtpccc for that, I noticed that you're using GPU with mulifunction=on in the message you provide.

> I'm also attaching the containerd logs for your reference. [containerd.error.2024-09-29-18-27-12.log](https://github.com/user-attachments/files/17178872/containerd.error.2024-09-29-18-27-12.log)
>
I notice there's a known error message similar to [the fixed issue #10276](https://github.com/kata-containers/kata-containers/pull/10276). And I checked your first log `2024-09-29-18-03-17.log` and find that you're using kata 3.8.0 with commit ID `version `3.8.0 (commit 09a13da8ece6f5c1f80703e9331d986a5994178d)` at `2024-09-29.18:03:17.644084137+0800` before  the commit ID `d0968032f75a3ab43327927d52b199b7af2811f4`which fixed the error 
```
panic: assignment to entry in nil map
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: goroutine 28 [running]:
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).siblingAnnotation(0xc0002a4420, {0xc00030e3c0, 0xc}, {0xc0004347b0?, 0x599704f6ee80?, 0x0?})
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1013 +0x1ab
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).annotateContainerWithVFIOMetadata(0xc0002a4420, {0x599704dfd700, 0xc000575778})
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:994 +0x6f4
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).create(0xc0002a4420, {0x5997050cd6f0, 0xc0005106c0})
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1045 +0x48b
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).createContainers(0xc0004baea0, {0x5997050cd6f0, 0xc0002cc8a0})
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:1899 +0x3d0
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.createSandboxFromConfig({_, _}, {0xc0002cc390, {0x0, 0x0}, {0x599704b19563, 0x4}, {0xc0002ec378, 0x6}, {0x0, ...}, ...}, ...)
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/api.go:110 +0x41b
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.CreateSandbox({_, _}, {0xc0002cc390, {0x0, 0x0}, {0x599704b19563, 0x4}, {0xc0002ec378, 0x6}, {0x0, ...}, ...}, ...)
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/api.go:51 +0x13a
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*VCImpl).CreateSandbox(_, {_, _}, {0xc0002cc390, {0x0, 0x0}, {0x599704b19563, 0x4}, {0xc0002ec378, 0x6}, ...}, ...)
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/implementation.go:35 +0x5d
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/pkg/katautils.CreateSandbox({_, _}, {_, _}, {{0xc0004b5c57, 0x5}, 0xc0000a1210, 0xc0002244f8, {0x0, 0x0}, ...}, ...)
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/katautils/create.go:170 +0x7eb
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.create({0x5997050cd6f0, 0xc0000b0de0}, 0xc0000e0c60, 0xc000000240?)
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/create.go:194 +0xda5
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Create.func2()
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:428 +0x2c
Sep 29 17:30:01 pve-host-sz01 containerd[1451]: created by github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Create in goroutine 27
Sep 29 17:30:01 pve-host-sz01 containerd[1451]:         /home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:427 +0x47c
```

**Comment by acblbtpccc** [comment]
Dear @Apokleos,

Thanks very much for your quick reply! I also tried kata 3.9, and also failed with error 
"ctr: failed to create shim task: QMP command failed: vfio 0000:03:00.0: failed to setup container for group 24: memory listener initialization failed: Region dimm1: vfio_dma_map(0x555556d05a90, 0x100000000, 0xf80000000, 0x74c02fc00000) = -14 (Bad address): unknown"

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/db25948b-1498-4f59-8b36-8974f799d6ea">

Would you be able to provide any additional advice or suggestions on how to resolve this issue?

Thank you for your continued assistance.


The related log files are as follows:
[kata-collect-data.sh.2024-09-30-02-58-34.log](https://github.com/user-attachments/files/17180831/kata-collect-data.sh.2024-09-30-02-58-34.log)
[containerd.errors.2024-09-30-03-06.log](https://github.com/user-attachments/files/17180834/containerd.errors.2024-09-30-03-06.log)

**Comment by yuxi191231** [comment]
> Dear @Apokleos,
> 
> Thanks very much for your quick reply! I also tried kata 3.9, and also failed with error "ctr: failed to create shim task: QMP command failed: vfio 0000:03:00.0: failed to setup container for group 24: memory listener initialization failed: Region dimm1: vfio_dma_map(0x555556d05a90, 0x100000000, 0xf80000000, 0x74c02fc00000) = -14 (Bad address): unknown"
> 
> <img alt="image" width="1193" src="https://private-user-images.githubusercontent.com/94864107/371883970-db25948b-1498-4f59-8b36-8974f799d6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjQ2MDAsIm5iZiI6MTcyOTU2NDMwMCwicGF0aCI6Ii85NDg2NDEwNy8zNzE4ODM5NzAtZGIyNTk0OGItMTQ5OC00ZjU5LThiMzYtODk3NGY3OTlkNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAyMzE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMjY5N2M0MWI5OTFmMDljOGFkZjQzNzFkYmE4NTMyNzkwMmY3ZmNmNDIyNDA1ZmQwMDZjNjRjZWY4ODFlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MDR2jG70ZOWpBT2I2oMJIZFga4c2XoI2hHA_0XImZn0">
> Would you be able to provide any additional advice or suggestions on how to resolve this issue?
> 
> Thank you for your continued assistance.
> 
> The related log files are as follows: [kata-collect-data.sh.2024-09-30-02-58-34.log](https://github.com/user-attachments/files/17180831/kata-collect-data.sh.2024-09-30-02-58-34.log) [containerd.errors.2024-09-30-03-06.log](https://github.com/user-attachments/files/17180834/containerd.errors.2024-09-30-03-06.log)

Hello, I have the same problem, have you solved it?

**Comment by yuxi191231** [comment]
Increase the /dev/shm mount size. Guest memory is backed by shared memory
You can try this method. It works for me. And I use Ubuntu.
