### ISSUE TITLE
Spark k8s cluster mode with kata runtime

### ISSUE THREAD

**Issue by qzheng527** [kata-containers/kata-containers#10429]
I have a working k8s cluster with kata runtime. Some applications such as nignx and kserve works fine on this cluser.
But when I tried Spark cluster mode with **spark-submit** by kata runtime,  I got below error in spark driver pod.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.spark.deploy.SparkSubmitArguments.$anonfun$loadEnvironmentArguments$5(SparkSubmitArguments.scala:163)
        at scala.Option.orElse(Option.scala:447)
        at org.apache.spark.deploy.SparkSubmitArguments.loadEnvironmentArguments(SparkSubmitArguments.scala:163)
        at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:118)
        at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1094)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1094)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.UnknownHostException: : : Name or service not known
        at java.base/java.net.InetAddress.getLocalHost(Unknown Source)
        at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:1045)
        at org.apache.spark.util.Utils$.localIpAddress$lzycompute(Utils.scala:1038)
        at org.apache.spark.util.Utils$.localIpAddress(Utils.scala:1038)
        at org.apache.spark.util.Utils$.$anonfun$localCanonicalHostName$1(Utils.scala:1095)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.util.Utils$.localCanonicalHostName(Utils.scala:1095)
        at org.apache.spark.internal.config.package$.<init>(package.scala:1044)
        at org.apache.spark.internal.config.package$.<clinit>(package.scala)
        ... 10 more
Caused by: java.net.UnknownHostException: : Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
        at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
        ... 19 more
```
It worked fine if not setting kata runtime. And I tried to exec into the pod, compared the files ( **/etc/hosts, /etc/resolve.conf**) content between kata runtime and runc, they are same.
Are there any special settings required for spark running on kata?
Or is there any verified how-to docs for spark running on kata?

Below are my spark test command and driver template pod file.
```
${SPARK_HOME}/bin/spark-submit \
    --master k8s://https://${kubernetes_master_url}:6443 \
    --deploy-mode cluster \
    --name spark-pi \
    --class org.apache.spark.examples.SparkPi \
    --conf spark.executor.instances=1 \
    --conf spark.kubernetes.container.image=apache/spark:3.4.3 \
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
    --conf spark.kubernetes.driver.podTemplateFile=./driver.yaml \
    --conf spark.kubernetes.executor.podTemplateFile=./executor.yaml \
    local:/opt/spark/examples/jars/spark-examples_2.12-3.4.3.jar
```

``` driver.yaml
apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  runtimeClassName: kata
  containers:
  - name: spark-example
    imagePullPolicy: IfNotPresent
```

**Comment by fidencio** [comment]
What version of Kata Containers you're using?
I have the feeling you're using either 3.8.0 or 3.9.0, which has a bug setting up the hostname inside the container.

Could you give it a try with Kata Containers 3.7.0?  If it works, we'll have the fix as part of 3.10.0.

**Comment by qzheng527** [comment]
@fidencio I used Kata 3.9.0. I will try 3.7.0. Thanks for reply.

**Comment by qzheng527** [comment]
It works fine on kata 3.7.0.
I close this issue right now and will try on 3.10.0 once it is published.

**Comment by fidencio** [comment]
3.10.0 was released Yesterday, please, give it a try.

**Comment by qzheng527** [comment]
@fidencio Spark + Kata 3.10.0 works fine.
