### ISSUE TITLE
OCI hooks are broken in Agent 2.0

### ISSUE THREAD

**Issue by mxpv** [kata-containers/kata-containers#1348]
We should rewrite fork/child code as it doesn't work well with Tokio (and may cause deadlocks).
It looks like OCI hooks ([execute_hook](https://github.com/kata-containers/kata-containers/blob/main/src/agent/rustjail/src/container.rs#L1520)) are currently broken in Rust version of the Agent.

I wrote the following unit test which hangs on my env:
``` rust
    #[tokio::test]
    async fn test_execute_hook() {
        println!("running test");
        execute_hook(
            &slog_scope::logger(),
            &Hook {
                path: "/kata-containers/src/agent/rustjail/audit.sh".to_string(),
                args: vec!["audit.sh".to_string(), "test_type".to_string()],
                env: vec![],
                timeout: None,
            },
            &OCIState {
                version: "".to_string(),
                id: "".to_string(),
                status: "".to_string(),
                pid: 0,
                bundle: "".to_string(),
                annotations: Default::default(),
            },
        )
        .await
        .unwrap();
    }
```

Output:
```
$ cargo test container::tests::test_execute_hook -- --nocapture

unning 1 test
running test
before fork
thread 'container::tests::test_execute_hook' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', rustjail/src/container.rs:1606:22

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'container::tests::test_execute_hook' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', rustjail/src/container.rs:1683:26

test container::tests::test_execute_hook ... test container::tests::test_execute_hook has been running for over 60 seconds

... never ends
```

script being tested:
```
cat ./audit.sh 

#!/bin/sh
read line
echo "$(date) input: $line" >> /tmp/test.log
```

cc: @egernst @Tim-Zhang

**Comment by Tim-Zhang** [comment]
@mxpv I will look into it.
