### ISSUE TITLE
TestIoCopy is failing randonly in the CI

### ISSUE THREAD

**Issue by devimc** [kata-containers/kata-containers#2042]
```
=== RUN   TestIoCopy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x47e62b]

goroutine 210 [running]:
io.copyBuffer(0x7feeb4ba6398, 0xc000367c80, 0x0, 0x0, 0xc00064a000, 0x8000, 0x8000, 0x11784e0, 0x0, 0x7feeb4ba6398)
	/opt/hostedtoolcache/go/1.15.13/x64/src/io/io.go:409 +0x10b
io.CopyBuffer(0x7feeb4ba6398, 0xc000367c80, 0x0, 0x0, 0xc00064a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.13/x64/src/io/io.go:382 +0x8c
github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2.ioCopy.func1(0x7feeb4ba63d8, 0xc000367c80, 0xc0003c8030, 0xc000500060, 0xc0003bea70)
	/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2/stream.go:96 +0x152
created by github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2.ioCopy
	/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2/stream.go:93 +0x1c5
FAIL	github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2	8.515s
=== RUN   TestNewNetmon
```

see https://github.com/kata-containers/kata-containers/pull/2041/checks?check_run_id=2831897753

cc @littlejawa

**Comment by littlejawa** [comment]
@devimc - thanks for raising this.
I've just run the proposed fix in a loop, and didn't cause the problem anymore (running it 30+ times).
Before that, I was seeing it about 1 out of 5 tries.
