### ISSUE TITLE
watcher::tests::create_tmpfs fails occasionally

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#2833]
upon running `cargo test` as root in `src/agent`, after usually a couple of attempts:
```
thread 'watcher::tests::create_tmpfs' panicked at 'assertion failed: is_mounted(WATCH_MOUNT_POINT_PATH).unwrap()', src/watcher.rs:990:9
```

or
```
thread 'watcher::tests::create_tmpfs' panicked at 'assertion failed: !is_mounted(WATCH_MOUNT_POINT_PATH).unwrap()', src/watcher.rs:993:9
```

branched out from #2809
seen across multiple architectures and distros
@sameo @egernst @mxpv can I bother one of you for a look?

**Comment by Jakob-Naucke** [comment]
Fixed by #2844
