### ISSUE TITLE
TestSandboxSetSandboxAndContainerState test failing on ARM / aarch64

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3316]
From http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/2946/console (https://github.com/kata-containers/kata-containers/pull/3297#issuecomment-997956941):

```
=== RUN   TestCreateSandboxEmptyID
--- PASS: TestCreateSandboxEmptyID (0.00s)
=== RUN   TestSandboxSetSandboxAndContainerState
    sandbox_test.go:339: 
        	Error Trace:	sandbox_test.go:339
        	Error:      	Received unexpected error:
        	            	open /tmp/vc/mockfs/sbs/7f49d00d-1995-4156-8c79-5f5ab24ce138: no such file or directory
        	Test:       	TestSandboxSetSandboxAndContainerState
--- FAIL: TestSandboxSetSandboxAndContainerState (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x942a4c]

goroutine 655 [running]:
testing.tRunner.func1.2({0xa32ae0, 0x13b2fa0})
	/usr/local/go/src/testing/testing.go:1209 +0x258
testing.tRunner.func1(0x4000c8b040)
	/usr/local/go/src/testing/testing.go:1212 +0x278
panic({0xa32ae0, 0x13b2fa0})
	/usr/local/go/src/runtime/panic.go:1038 +0x224
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.testCheckSandboxOnDiskState(...)
	/home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox_test.go:227
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.TestSandboxSetSandboxAndContainerState(0x4000c8b040)
	/home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox_test.go:341 +0x64c
testing.tRunner(0x4000c8b040, 0xbaad70)
	/usr/local/go/src/testing/testing.go:1259 +0x100
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x350
FAIL	github.com/kata-containers/kata-containers/src/runtime/virtcontainers	2.191s
?   	github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/api	[no test files]
=== RUN   TestGetBackingFile
--- PASS: TestGetBackingFile (0.00s)
```

This _might_ be related to #2987.

**Comment by jongwu** [comment]
Thanks @jodh-intel -, maybe the race condition leads to that failure. We should let tests run sequentially.
Any idea? @Jakob-Naucke

**Comment by Jakob-Naucke** [comment]
@jongwu I can only tell you that `go test -p 1` did *not* fix the issue for me :/
