### ISSUE TITLE
Attempting to build custom qemu (6.1.0) on Debian - with `checkinstall`

### ISSUE THREAD

**Issue by develop-Greenant** [kata-containers/kata-containers#3464]
I am attempting to install kata-containers on Debian Bullseye with a simple packaging approach using `checkinstall`.  Hopefully this can provide a pathway that will contribute to debian packaging in the future.

So far, I have used the [instructions here](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md) with success to build `kata-runtime`, `kata-shim`, `kata-proxy` and copied the vm-images from the kata-static sources.  I am using `checkinstall` instead of `make install` so that apt packages are created of each component.

Finally, I have been attempting to build `kata-qemu-custom` using [instructions here](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#build-a-custom-qemu) with a couple of little modifications.

1. install dependencies

```bash
aptitude install apt-utils \
autoconf \
automak \
bc \
bison \
ca-certificates \
cpio \
flex \
gawk \
libaudit-dev \
libblkid-dev \
libcap-dev \
libcap-ng-dev \
libdw-dev \
libelf-dev \
libffi-dev \
libglib2.0-0 \
libglib2.0-dev \
libglib2.0-dev \
git \
libltdl-dev \
libmount-dev \
libpixman-1-dev \
libselinux1-dev \
libtool \
make \
ninja-build \
pkg-config \
libseccomp-dev \
libseccomp2 \
python3 \
python3-dev \
rsync \
zlib1g-dev\ 
```

```bash
apt install librados-dev \
libpmem-dev \
librbd-dev
```

- using python v3.9.2

2. build commands

- get sources and set version to 6.1.0

```bash
source ${GOPATH}/src/github.com/kata-containers/kata-containers/tools/packaging/scripts/lib.sh
# added version manually `yq` command not available
qemu_version=v6.1.0
# previously:
#qemu_version=$(get_from_kata_deps "assets.hypervisor.qemu.version")
echo ${qemu_version}
```

- get qemu sources

```bash
go get -d github.com/qemu/qemu
cd ${GOPATH}/src/github.com/qemu/qemu
git checkout ${qemu_version}
your_qemu_directory=${GOPATH}/src/github.com/qemu/qemu
```

- set packaging dir:

```bash
go get -d github.com/kata-containers/kata-containers
packaging_dir="${GOPATH}/src/github.com/kata-containers/kata-containers/tools/packaging
```

- apply patches:

```bash
 cd $your_qemu_directory
$packaging_dir/scripts/apply_patches.sh $packaging_dir/qemu/patches/6.1.x/
```

- build with `checkinstall`

```bash
cd $your_qemu_directory
$packaging_dir/scripts/configure-hypervisor.sh kata-qemu > kata.cfg
eval ./configure "$(cat kata.cfg)"
make -j $(nproc)
# use checkinstall instead of make instalk
#sudo -E make install
checkinstall
```

The requirements are fulfilled and `make -j $(nproc)` runs fine, however `checkinstall` fails on file copy it seems...

```
Installing with make install...

========================= Installation results ===========================
changing dir to build for make "install"...
make[1]: Entering directory '/root/go/src/github.com/qemu/qemu/build'
  GIT     ui/keycodemapdb meson
[1/8] Generating qemu-version.h with a meson_exe.py custom command
[1/2] Installing files.
Traceback (most recent call last):
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 544, in run
    installer.do_install(datafilename)
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 362, in do_install
    self.install_targets(d)
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 472, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(d.dirmaker, outdir))
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 277, in do_copyfile
    shutil.copystat(from_file, to_file)
  File "/usr/lib/python3.9/shutil.py", line 375, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
FileNotFoundError: [Errno 2] No such file or directory
Installing trace/trace-events-all to /usr/share/kata-qemu/qemu
FAILED: meson-install 
/usr/bin/python3 /root/go/src/github.com/qemu/qemu/meson/meson.py install --no-rebuild
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:156: run-ninja] Error 1
make[1]: Leaving directory '/root/go/src/github.com/qemu/qemu/build'
make: *** [GNUmakefile:11: install] Error 2

****  Installation failed. Aborting package creation.
```

I believe that the `shutil.copystat(from_file, to_file)` is not getting the correct source/destination file nut unsure how to proceed.

Any ideas on how to fix that issue?
Alternatively, I may try with the packaged qemu and see if that works (probably symlinking the system qemu to the kata expected location)

**Comment by Jakob-Naucke** [comment]
Hm, `checkinstall` of QEMU 6.1.0 works for me (tested on Ubuntu 20.04 though, don't have a Debian instance lying around right now). While I didn't need it, it looks as if your `checkinstall` needs `utime`, which is provided by the `atfs` package. Can you also try doing this just with QEMU so we can see whether this is due to Kata? (`./configure --target-list=$(uname -m)-softmmu`, `make`, `checkinstall`).

**Comment by develop-Greenant** [comment]
@Jakob-Naucke thanks for the tip regarding the `atfs` library.  
I installed that package and also all the optional requirements listed here:
https://wiki.qemu.org/Hosts/Linux#Fedora_Linux_.2F_Debian_GNU_Linux_.2F_Ubuntu_Linux_.2F_Linux_Mint_distributions

Unfortunately I still got the same error.

Trying your suggestion, with no kata patches on `qemu` v6.1.0:

```bash
./configure --target-list=$(uname -m)-softmmu
make -j $(nproc)
checkinstall
```

`configure` and `make` execute without error.  But I am getting same error with `checkinstall`

```
Installing with make install...

========================= Installation results ===========================
changing dir to build for make "install"...
make[1]: Entering directory '/root/go/src/github.com/qemu/qemu/build'
  GIT     ui/keycodemapdb meson tests/fp/berkeley-testfloat-3 tests/fp/berkeley-softfloat-3 dtc capstone slirp
[1/20] Generating qemu-version.h with a meson_exe.py custom command
[1/2] Installing files.
Traceback (most recent call last):
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 544, in run
    installer.do_install(datafilename)
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 362, in do_install
    self.install_targets(d)
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 472, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(d.dirmaker, outdir))
  File "/root/go/src/github.com/qemu/qemu/meson/mesonbuild/minstall.py", line 277, in do_copyfile
    shutil.copystat(from_file, to_file)
  File "/usr/lib/python3.9/shutil.py", line 375, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
FileNotFoundError: [Errno 2] No such file or directory
Installing subdir /root/go/src/github.com/qemu/qemu/qga/run to /usr/local/var/run
Installing trace/trace-events-all to /usr/local/share/qemu
FAILED: meson-install 
/usr/bin/python3 /root/go/src/github.com/qemu/qemu/meson/meson.py install --no-rebuild
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:156: run-ninja] Error 1
make[1]: Leaving directory '/root/go/src/github.com/qemu/qemu/build'
make: *** [GNUmakefile:11: install] Error 2

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

```

so I guess this looks like a general `qemu` build error rather than being kata specific...

**Comment by develop-Greenant** [comment]
filed bug report at qemu repo [here](https://gitlab.com/qemu-project/qemu/-/issues/848)

also tried with v6.1.1 (as bug reports only accepted on last 2 releases)

**Comment by Jakob-Naucke** [comment]
thanks @develop-Greenant -- closing.
