### ISSUE TITLE
test_do_write_stream fails frequently

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#4103]
Sometimes static check complains this error(Full link: https://github.com/kata-containers/kata-containers/runs/6014924735?check_suite_focus=true):

It's not a 100% issue.

```

test rpc::tests::test_append_guest_hooks ... ok
test rpc::tests::test_add_arp_neighbors ... ok
test rpc::tests::test_get_memory_info ... ok
test rpc::tests::test_load_kernel_module ... ok
test rpc::tests::test_update_interface ... ok
test rpc::tests::test_update_routes ... ok
test rpc::tests::test_verify_cid ... ok
test sandbox::tests::add_and_get_container ... ok
thread 'sandbox::tests::add_guest_hooks' panicked at 'assertion failed: s.hooks.as_ref().unwrap().prestart.len() == 1', src/sandbox.rs:798:9
stack backtrace:
test rpc::tests::test_do_write_stream ... ok
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: kata_agent::sandbox::tests::add_guest_hooks::{{closure}}::{{closure}}
             at ./src/sandbox.rs:798:9
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
   6: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:62
   7: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  10: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  11: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  12: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:39
  13: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:29
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  15: tokio::runtime::basic_scheduler::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:5
  16: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:230:9
  17: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:501:9
  18: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:186:24
  19: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:461:46
  20: kata_agent::sandbox::tests::add_guest_hooks::{{closure}}
             at ./src/sandbox.rs:800:9
  21: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  22: serial_test::serial_core
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/serial_test-0.5.1/src/lib.rs:64:5
  23: kata_agent::sandbox::tests::add_guest_hooks
             at ./src/sandbox.rs:780:5
  24: kata_agent::sandbox::tests::add_guest_hooks::{{closure}}
             at ./src/sandbox.rs:781:11
  25: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test sandbox::tests::add_guest_hooks ... FAILED
test sandbox::tests::get_container_entry_exist ... ok
test sandbox::tests::get_container_no_entry ... ok
INFO: skipping kata_agent::sandbox::tests which needs root
```

**Comment by liubin** [comment]
And here https://github.com/kata-containers/kata-containers/runs/6123318231?check_suite_focus=true

```

test sandbox::tests::test_find_container_process ... ok
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
test sandbox::tests::test_sandbox_set_destroy ... ok
INFO: skipping kata_agent::sandbox::tests which needs root
test sandbox::tests::unset_and_remove_sandbox_storage ... ok
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: kata_agent::rpc::tests::test_do_write_stream::{{closure}}
             at ./src/rpc.rs:2117:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
test sandbox::tests::unset_sandbox_storage ... ok
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
   7: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:62
   8: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  11: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  12: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:39
  14: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:29
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  16: tokio::runtime::basic_scheduler::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:5
  17: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:230:9
  18: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:501:9
  19: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:186:24
  20: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:461:46
  21: kata_agent::rpc::tests::test_do_write_stream
             at ./src/rpc.rs:2113:9
  22: kata_agent::rpc::tests::test_do_write_stream::{{closure}}
             at ./src/rpc.rs:2042:11
test sandbox::tests::update_shared_pidns ... ok
  23: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
INFO: task completed
  24: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test rpc::tests::test_do_write_stream ... FAILED
test signal::tests::test_setup_signal_handler ... ok
test uevent::tests::test_wait_for_uevent ... ok
```

**Comment by liubin** [comment]
Sometimes Bad file descriptor:

> 2022-06-29T13:45:50.4393888Z thread 'rpc::tests::test_update_container_namespaces' panicked at 'called `Result::unwrap()` on an `Err` value: Bad file descriptor (os error 9)', src/rpc.rs:2422:53

**Comment by liubin** [comment]
Recently get many `Bad file descriptor` errors.

Logs from https://github.com/kata-containers/kata-containers/runs/7683866741?check_suite_focus=true

```
test rpc::tests::test_is_signal_handled ... ok
thread 'rpc::tests::test_load_kernel_module' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', library/std/src/process.rs:1862:21
stack backtrace:
test rpc::tests::test_do_write_stream ... ok
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: std::process::Child::wait_with_output
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/process.rs:1862:17
   5: std::process::Command::output::{{closure}}
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/process.rs:912:27
   6: core::result::Result<T,E>::and_then
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:966:22
   7: std::process::Command::output
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/process.rs:909:9
   8: kata_agent::rpc::load_kernel_module
             at ./src/rpc.rs:1987:18
   9: kata_agent::rpc::tests::test_load_kernel_module
             at ./src/rpc.rs:2079:22
  10: kata_agent::rpc::tests::test_load_kernel_module::{{closure}}
             at ./src/rpc.rs:2072:5
  11: core::ops::function::FnOnce::call_once
```

**Comment by liubin** [comment]
Not sure but may be related, not GitHub actions, but a CI job:
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/2340/console

>. 05:53:48 test sandbox::tests::update_shared_pidns ... ok
05:53:48 thread 'watcher::tests::create_tmpfs' panicked at 'assertion failed: is_mounted(WATCH_MOUNT_POINT_PATH).unwrap()', src/watcher.rs:1279:9
05:53:48 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
05:53:48 test watcher::tests::create_tmpfs ... FAILED
