### ISSUE TITLE
Cloud Hypervisor vfio CI test is failing

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#8244]
See for example: #8155, #8213.

Looking at the logs...

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x558bdc82e731]

goroutine 1 [running, locked to thread]:
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*cloudHypervisor).HotplugRemoveDevice(0xc000248600, {0x558bdcf21a78, 0xc000201620}, {0x558bdccb20a0?, 0xc0000406c0?}, 0x6)
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/clh.go:973 +0x431
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).HotplugRemoveDevice(0xc0001d0340, {0x558bdcf21a78, 0xc000201620}, {0x558bdcf28fe8?, 0xc0002733e0?}, {0x558bdca01163, 0x4})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:2054 +0x828
github.com/kata-containers/kata-containers/src/runtime/pkg/device/drivers.(*VFIODevice).Detach(0xc0002733e0, {0x558bdcf21a78, 0xc000201620}, {0x558bdcf25670, 0xc0001d0340})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/device/drivers/vfio.go:137 +0x2ff
github.com/kata-containers/kata-containers/src/runtime/pkg/device/manager.(*deviceManager).DetachDevice(0xc00037eaa0, {0x558bdcf21a78, 0xc000201620}, {0xc000246bc0, 0x10}, {0x558bdcf25670, 0xc0001d0340})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/device/manager/manager.go:228 +0x124
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).detachDevices(0xc000523340, {0x558bdcf21a78, 0xc000201620})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1413 +0x10a
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).stop(0xc000523340, {0x558bdcf21a78, 0xc0000e0990}, 0x1)
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1084 +0x9d6
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).StopContainer(0x558bdcf21a78?, {0x558bdcf21a78, 0xc0000e0990}, {0x7ffde9d73e57?, 0x10?}, 0x80?)
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:1579 +0x5e
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.CleanupContainer({0x558bdcf21a78?, 0xc00055ae40?}, {0x7ffde9d73e57, 0x16}, {0x7ffde9d73e57, 0x16}, 0x1)
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/api.go:143 +0x26f
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*VCImpl).CleanupContainer(0xc000224930?, {0x558bdcf21a78?, 0xc00055ae40?}, {0x7ffde9d73e57?, 0xc0000ca900?}, {0x7ffde9d73e57?, 0x558bdbeb41e5?}, 0x90?)
\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/implementation.go:42 +0x45
github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.cleanupContainer({0x558bdcf21a78, 0xc00055ae40}, {0x7ffde9d73e57, 0x16}, {0x7ffde9d73e57, 0x16}, {0xc0001b2000, 0x4c})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/utils.go:37 +0x2a5
github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Cleanup(0xc0004f2630, {0x558bdca08e69?, 0x9?})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:358 +0x46d
github.com/containerd/containerd/runtime/v2/shim.shimToManager.Stop({{0x558bdcf2ca90?, 0xc0004f2630?}, {0x558bdca1c7b4?, 0xc0000351f8?}}, {0x558bdcf21f48?, 0xc00008ca80?}, {0x30?, 0x558bdccf2980?})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go:213 +0x52
github.com/containerd/containerd/runtime/v2/shim.run({0x558bdcf21a78, 0xc00055aba0}, {0x0, 0x0}, 0x558bdcf0b490, {0x558bdca1c7b4, 0x15}, {0x1, 0x1, 0x0})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go:309 +0xc1b
github.com/containerd/containerd/runtime/v2/shim.Run({0x558bdca1c7b4, 0x15}, 0x558bdbd527fd?, {0xc0005bff28, 0x1, 0xc0000061a0?})
\t/home/runner/work/kata-containers/kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go:190 +0x1d7
main.main()
\t/home/runner/work/kata-containers/kata-containers/src/runtime/cmd/containerd-shim-kata-v2/main.go:31 +0x166
: exit status 2" id=vfio-guest-kernel-6946 namespace=default
```

<details>
<summary>Full log entry for CH hotplug remove error</summary>
2023-10-13T12:20:36.1821805Z Oct 13 12:20:34 test containerd[1783]: time="2023-10-13T12:20:34.341654305Z" level=warning msg="failed to clean up after shim disconnected" error="time=\"2023-10-13T12:20:34Z\" level=warning msg=\"Could not add /dev/mshv to the devices cgroup\" name=containerd-shim-v2 pid=1792 sandbox=vfio-guest-kernel-6946 source=cgroups\ntime=\"2023-10-13T12:20:34Z\" level=warning msg=\"Could not add device to the &{%!s(*v2.Manager=&{/sys/fs/cgroup /sys/fs/cgroup/vc}) /vc %!s(*specs.LinuxCPU=<nil>) [{%!s(bool=true) c %!s(*int64=0xc000200f08) %!s(*int64=0xc000200f10) rwm} {%!s(bool=true) c %!s(*int64=0xc000200f38) %!s(*int64=0xc000200f40) rwm} {%!s(bool=true) c %!s(*int64=0xc000200f68) %!s(*int64=0xc000200f70) rwm} {%!s(bool=true) c %!s(*int64=0xc000200f98) %!s(*int64=0xc000200fa0) rwm} {%!s(bool=true) c %!s(*int64=0xc000200fc8) %!s(*int64=0xc000200fd0) rwm} {%!s(bool=true) c %!s(*int64=0xc000200ff8) %!s(*int64=0xc000201000) rwm} {%!s(bool=true) c %!s(*int64=0xc000201028) %!s(*int64=0xc000201030) rwm} {%!s(bool=true) c %!s(*int64=0xc000201058) %!s(*int64=0xc000201060) rwm} {%!s(bool=true) c %!s(*int64=0xc000201118) %!s(*int64=0xc000201120) rwm} {%!s(bool=true) c %!s(*int64=0xc000201148) %!s(*int64=0xc000201150) rwm} {%!s(bool=true) c %!s(*int64=0xc000201178) %!s(*int64=0xc000201180) rwm} {%!s(bool=true) c %!s(*int64=0xc0002462a0) %!s(*int64=0xc0002462a8) m} {%!s(bool=true) b %!s(*int64=0xc0002462a0) %!s(*int64=0xc0002462a8) m} {%!s(bool=true) c %!s(*int64=0xc0002462b0) %!s(*int64=0xc0002462a8) rwm} {%!s(bool=true) c %!s(*int64=0xc0002462b8) %!s(*int64=0xc0002462c0) rwm}] {%!s(int32=0) %!s(uint32=0)}} controller\" device=\"&{0xc000201290 [0xc0000406c0]}\" error=\"no such file or directory\" name=containerd-shim-v2 pid=1792 sandbox=vfio-guest-kernel-6946 source=virtcontainers subsystem=sandbox\npanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x558bdc82e731]\n\ngoroutine 1 [running, locked to thread]:\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*cloudHypervisor).HotplugRemoveDevice(0xc000248600, {0x558bdcf21a78, 0xc000201620}, {0x558bdccb20a0?, 0xc0000406c0?}, 0x6)\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/clh.go:973 +0x431\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).HotplugRemoveDevice(0xc0001d0340, {0x558bdcf21a78, 0xc000201620}, {0x558bdcf28fe8?, 0xc0002733e0?}, {0x558bdca01163, 0x4})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:2054 +0x828\ngithub.com/kata-containers/kata-containers/src/runtime/pkg/device/drivers.(*VFIODevice).Detach(0xc0002733e0, {0x558bdcf21a78, 0xc000201620}, {0x558bdcf25670, 0xc0001d0340})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/device/drivers/vfio.go:137 +0x2ff\ngithub.com/kata-containers/kata-containers/src/runtime/pkg/device/manager.(*deviceManager).DetachDevice(0xc00037eaa0, {0x558bdcf21a78, 0xc000201620}, {0xc000246bc0, 0x10}, {0x558bdcf25670, 0xc0001d0340})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/device/manager/manager.go:228 +0x124\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).detachDevices(0xc000523340, {0x558bdcf21a78, 0xc000201620})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1413 +0x10a\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Container).stop(0xc000523340, {0x558bdcf21a78, 0xc0000e0990}, 0x1)\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/container.go:1084 +0x9d6\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).StopContainer(0x558bdcf21a78?, {0x558bdcf21a78, 0xc0000e0990}, {0x7ffde9d73e57?, 0x10?}, 0x80?)\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:1579 +0x5e\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.CleanupContainer({0x558bdcf21a78?, 0xc00055ae40?}, {0x7ffde9d73e57, 0x16}, {0x7ffde9d73e57, 0x16}, 0x1)\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/api.go:143 +0x26f\ngithub.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*VCImpl).CleanupContainer(0xc000224930?, {0x558bdcf21a78?, 0xc00055ae40?}, {0x7ffde9d73e57?, 0xc0000ca900?}, {0x7ffde9d73e57?, 0x558bdbeb41e5?}, 0x90?)\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/virtcontainers/implementation.go:42 +0x45\ngithub.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.cleanupContainer({0x558bdcf21a78, 0xc00055ae40}, {0x7ffde9d73e57, 0x16}, {0x7ffde9d73e57, 0x16}, {0xc0001b2000, 0x4c})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/utils.go:37 +0x2a5\ngithub.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Cleanup(0xc0004f2630, {0x558bdca08e69?, 0x9?})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:358 +0x46d\ngithub.com/containerd/containerd/runtime/v2/shim.shimToManager.Stop({{0x558bdcf2ca90?, 0xc0004f2630?}, {0x558bdca1c7b4?, 0xc0000351f8?}}, {0x558bdcf21f48?, 0xc00008ca80?}, {0x30?, 0x558bdccf2980?})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go:213 +0x52\ngithub.com/containerd/containerd/runtime/v2/shim.run({0x558bdcf21a78, 0xc00055aba0}, {0x0, 0x0}, 0x558bdcf0b490, {0x558bdca1c7b4, 0x15}, {0x1, 0x1, 0x0})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go:309 +0xc1b\ngithub.com/containerd/containerd/runtime/v2/shim.Run({0x558bdca1c7b4, 0x15}, 0x558bdbd527fd?, {0xc0005bff28, 0x1, 0xc0000061a0?})\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go:190 +0x1d7\nmain.main()\n\t/home/runner/work/kata-containers/kata-containers/src/runtime/cmd/containerd-shim-kata-v2/main.go:31 +0x166\n: exit status 2" id=vfio-guest-kernel-6946 namespace=default
 </details>

/cc @jepio, @amshinde, @fidencio, @likebreath.

**Comment by likebreath** [comment]
Do we know when (e.g. which commit) this started to fail?

**Comment by jepio** [comment]
As far as i can tell, this has been failing sporadically for a long time, but we only started seeing this in the logs when the test was moved to GHA.
