### ISSUE TITLE
containerd-shim-kata-v2 ran into the below panic when "enable_tracing = true"

### ISSUE THREAD

**Issue by liubocflt** [kata-containers/kata-containers#9102]
Hi devs,

# Description of problem

While running kata release 3.1, I followed the tracing doc (jaeger and kata) and enabled tracing capability of "runtime" only.
However, on container exit `containerd-shim-kata-v2` ran into the below panic, although jeager collector did receive some time span before panic.
```
SAGE" : "time=\"2024-02-15T23:55:03.947563413Z\" level=warning msg=\"clh.VmmPingGet API call failed\" error=\"Get \\\"http://localhost/api/v1/vmm.ping\\\": dial unix /run/user/1479/run/vc/vm/65e18f8a88fc48e14af0a35853a0a0faa8b5924f9185cf611a1babf153de5308/clh-api.sock: connect: no such file or directory\" name=containerd-shim-v2 pid=728215 sandbox=65e18f8a88fc48e14af0a3
SAGE" : "time=\"2024-02-15T23:55:04.336415771Z\" level=info msg=\"RunPodSandbox for &PodSandboxMetadata{Name:liubo-pod-fb59dc8db-v58pp,Uid:a9002547-b2d8-4fe4-9080-b2d31d95c56e,Namespace:liubo-parallel-128,Attempt:9,} returns sandbox id \\\"65e18f8a88fc48e14af0a35853a0a0faa8b5924f9185cf611a1babf153de5308\\\"\"" }
SAGE" : "time=\"2024-02-15T23:55:04.903086619Z\" level=info msg=\"PullImage \\\"alpine:latest\\\"\"" }
SAGE" : "time=\"2024-02-15T23:55:05.038197216Z\" level=info msg=\"ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}\"" }
SAGE" : "time=\"2024-02-15T23:55:05.042279370Z\" level=info msg=\"ImageUpdate event &ImageUpdate{Name:sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}\"" }
SAGE" : "time=\"2024-02-15T23:55:05.045503966Z\" level=info msg=\"ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine:latest,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}\"" }
SAGE" : "time=\"2024-02-15T23:55:05.048906528Z\" level=info msg=\"ImageUpdate event &ImageUpdate{Name:docker.io/library/alpine@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}\"" }
SAGE" : "time=\"2024-02-15T23:55:05.049248885Z\" level=info msg=\"PullImage \\\"alpine:latest\\\" returns image reference \\\"sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd\\\"\"" }
SAGE" : "time=\"2024-02-15T23:55:05.050534158Z\" level=info msg=\"CreateContainer within sandbox \\\"65e18f8a88fc48e14af0a35853a0a0faa8b5924f9185cf611a1babf153de5308\\\" for container &ContainerMetadata{Name:liubo059-init,Attempt:0,}\"" }
SAGE" : "time=\"2024-02-15T23:55:05.069389089Z\" level=info msg=\"CreateContainer within sandbox \\\"65e18f8a88fc48e14af0a35853a0a0faa8b5924f9185cf611a1babf153de5308\\\" for &ContainerMetadata{Name:liubo059-init,Attempt:0,} returns container id \\\"ffd2cbbda3954afb378933b387fa74172fcbf0d1907310b392fb63055cd429a0\\\"\"" }
SAGE" : "time=\"2024-02-15T23:55:05.069813079Z\" level=info msg=\"StartContainer for \\\"ffd2cbbda3954afb378933b387fa74172fcbf0d1907310b392fb63055cd429a0\\\"\"" }
SAGE" : "time=\"2024-02-15T23:55:05.127019738Z\" level=info msg=\"StartContainer for \\\"ffd2cbbda3954afb378933b387fa74172fcbf0d1907310b392fb63055cd429a0\\\" returns successfully\"" }
SAGE" : "panic: runtime error: invalid memory address or nil pointer dereference" }
SAGE" : "[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55ad4389b862]" }
SAGE" : "goroutine 2118 [running]:" }
SAGE" : "go.opentelemetry.io/otel/sdk/trace.(*TracerProvider).ForceFlush(0xc000168f00?, {0x55ad443aa988?, 0xc0002d6c00?})" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/go.opentelemetry.io/otel/sdk/trace/provider.go:187 +0x22" }
SAGE" : "github.com/kata-containers/kata-containers/src/runtime/pkg/katautils/katatrace.StopTracing({0x55ad443aa988, 0xc0002d6c00})" }
SAGE" : "/home//cc-kata-containers/src/runtime/pkg/katautils/katatrace/tracing.go:121 +0x65" }
SAGE" : "github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2.(*service).Shutdown(0xc0000b4d10, {0xc000319d00?, 0x10?}, 0xc000319d00)" }
SAGE" : "/home//cc-kata-containers/src/runtime/pkg/containerd-shim-v2/service.go:952 +0x48e" }
SAGE" : "github.com/containerd/containerd/runtime/v2/task.RegisterTaskService.func17({0x55ad443aa950, 0xc00045f3e0}, 0xc0002957c0)" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/github.com/containerd/containerd/runtime/v2/task/shim.pb.go:3568 +0x98" }
SAGE" : "github.com/containerd/ttrpc.defaultServerInterceptor({0x55ad443aa950?, 0xc00045f3e0?}, 0x17?, 0xc000337540?, 0x8?)" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/github.com/containerd/ttrpc/interceptor.go:45 +0x26" }
SAGE" : "github.com/containerd/ttrpc.(*serviceSet).dispatch(0xc0004f06c0, {0x55ad443aa950, 0xc00045f3e0}, {0xc0004766d8, 0x17}, {0xc00041a888, 0x8}, {0xc0001d0f00, 0x42, 0x50})" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/github.com/containerd/ttrpc/services.go:95 +0x1be" }
SAGE" : "github.com/containerd/ttrpc.(*serviceSet).call(0xc00047c488?, {0x55ad443aa950?, 0xc00045f3e0?}, {0xc0004766d8?, 0xc0004226c0?}, {0xc00041a888?, 0x55ad4439dc40?}, {0xc0001d0f00, 0x42, 0x50})" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/github.com/containerd/ttrpc/services.go:64 +0x71" }
SAGE" : "github.com/containerd/ttrpc.(*serverConn).run.func2(0x19)" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/github.com/containerd/ttrpc/server.go:438 +0xe5" }
SAGE" : "created by github.com/containerd/ttrpc.(*serverConn).run" }
SAGE" : "/home//cc-kata-containers/src/runtime/vendor/github.com/containerd/ttrpc/server.go:434 +0x7b1" }
SAGE" : "time=\"2024-02-15T23:55:05.140442808Z\" level=info msg=\"shim disconnected\" id=65e18f8a88fc48e14af0a35853a0a0faa8b5924f9185cf611a1babf153de5308" }
SAGE" : "time=\"2024-02-15T23:55:05.140452954Z\" level=info msg=\"shim disconnected\" id=ffd2cbbda3954afb378933b387fa74172fcbf0d1907310b392fb63055cd429a0" }
SAGE" : "time=\"2024-02-15T23:55:05.140482184Z\" level=warning msg=\"cleaning up after shim disconnected\" id=65e18f8a88fc48e14af0a35853a0a0faa8b5924f9185cf611a1babf153de5308 namespace=k8s.io" }
SAGE" : "time=\"2024-02-15T23:55:05.140496092Z\" level=info msg=\"cleaning up dead shim\"" }
```

# Expected result

no panic.

# Actual result

panic.

# Further information

Given that jaeger collector was able to receive timespan metrics before panic, the initialization of tracing stuff should have worked well.
The panic showed that ForceFlush ran into some invalid memory, by looking at the code, not sure how this could happen,
https://github.com/kata-containers/kata-containers/blob/ee57732fe08504773b1b5474f2248834ae1fbd66/src/runtime/vendor/go.opentelemetry.io/otel/sdk/trace/provider.go#L187

# Kata Containers survey

Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey

**Comment by liubocflt** [comment]
Is there known bugfix for this?

**Comment by liubocflt** [comment]
Still ran into the panic with 3.3.0-alpha0

**Comment by liubocflt** [comment]
https://github.com/kata-containers/kata-containers/blob/11b603e5f1a0920cee994290542feb79c056b3d3/src/runtime/vendor/go.opentelemetry.io/otel/sdk/trace/provider.go#L138

I dug it a bit and found out  `p` is `nil`, p is a global one though.
